### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by MakeMeCool** [arshsisodiya/helios-mirror#102]
### Geeting Error in my oracle VPS

[2022-07-29 09:32:16 +0000] [11] [INFO] Starting gunicorn 20.1.0
[2022-07-29 09:32:16 +0000] [11] [INFO] Listening at: http://0.0.0.0:80 (11)
[2022-07-29 09:32:16 +0000] [11] [INFO] Using worker: sync
[2022-07-29 09:32:16 +0000] [37] [INFO] Booting worker with pid: 37
2022-07-29 09:32:18,413 - bot - INFO - Generating BOT_SESSION_STRING
2022-07-29 09:32:18,421 - root - INFO - Initializing Aria2c
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 216, in <module>
    Popen(["megasdkrest", "--apikey", MEGA_API_KEY])
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'megasdkrest'
Exception ignored in: <function ClientSession.__del__ at 0xffff974430d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 347, in __del__
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1740, in call_exception_handler
  File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
NameError: name 'open' is not defined

**Comment by arshsisodiya** [comment]
You using my docker?

**Comment by MakeMeCool** [comment]
Yes using `arshsisodiya/helioskirepo:arm64`

**Comment by arshsisodiya** [comment]
Use arshsisodiya/helioskirepo:public

**Comment by MakeMeCool** [comment]
Using Oracle VPS. I also try with `arshsisodiya/helioskirepo:public` but getting error.

![image](https://user-images.githubusercontent.com/25415614/181876922-f18f4a78-df92-4a4b-8e17-de16deae2fe2.png)

**Comment by arshsisodiya** [comment]
Okey so you can't deploy right now on arm64 plateforms, i will update the docker in few days

**Comment by MakeMeCool** [comment]
ok

**Comment by NyiNyiTG** [comment]
same error

**Comment by KCPNLP2000** [comment]
Getting same error on DigitalOcean VPS

**Comment by KCPNLP2000** [comment]
**Getting following error**

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 617, in <module>
    botname = bot.username
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 387, in username
    return self.bot.username  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 366, in bot
    self._bot = self.get_me()
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 133, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 453, in get_me
    result = self._post('getMe', timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telegram/bot.py", line 298, in _post
    return self.request.post(
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 361, in post
    result = self._request_wrapper(
  File "/usr/local/lib/python3.8/dist-packages/telegram/utils/request.py", line 277, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized
Exception ignored in: <function ClientSession.__del__ at 0x7f5122e004c0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 347, in __del__
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1740, in call_exception_handler
  File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
  File "/usr/lib/python3.8/logging/__init__.py", line 1186, in emit
  File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
NameError: name 'open' is not defined
