### ISSUE TITLE
Could not cancel a progress

### ISSUE THREAD

**Issue by JiC54** [arshsisodiya/helios-mirror#116]
**When I try to cancel the download or upload progress, nothing happens, the downloading or uploading still continues. what could be the problem? I checked the logs, i got this:**

```
2022-08-18T10:22:27.289326+00:00 app[web.1]: 2022-08-18 10:22:27,289 - bot.helper.mirror_utils.upload_utils.pyrogramEngine - INFO - Cancelling Upload: She_Hulk_Attorney_at_Law_S01E01_1080p_10bit_WEBRip_6CH_x265_HEVC.mkv
2022-08-18T10:22:27.376050+00:00 app[web.1]: 2022-08-18 10:22:27,375 - bot - WARNING - ewww Message can't be deleted
2022-08-18T10:22:27.376556+00:00 app[web.1]: 2022-08-18 10:22:27,376 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
2022-08-18T10:22:27.376557+00:00 app[web.1]: Traceback (most recent call last):
2022-08-18T10:22:27.376558+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/ext/utils/promise.py", line 96, in run
2022-08-18T10:22:27.376558+00:00 app[web.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2022-08-18T10:22:27.376558+00:00 app[web.1]:   File "/usr/src/app/bot/modules/cancel_mirror.py", line 38, in cancel_mirror
2022-08-18T10:22:27.376559+00:00 app[web.1]:     dl.download().cancel_download()
2022-08-18T10:22:27.376559+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/pyrogramEngine.py", line 287, in cancel_download
2022-08-18T10:22:27.376559+00:00 app[web.1]:     self.__listener.onUploadError('your upload has been stopped!')
2022-08-18T10:22:27.376560+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 388, in onUploadError
2022-08-18T10:22:27.376560+00:00 app[web.1]:     e_str = error.replace('<', '').replace('>', '')
2022-08-18T10:22:27.376561+00:00 app[web.1]: UnboundLocalError: local variable 'error' referenced before assignment
```

**Comment by YourGirFriendsBF** [comment]
Join @MirrorSociety on Telegram and elaborate your issue there bro
