### ISSUE TITLE
Last-api error

### ISSUE THREAD

**Issue by HerokuLover** [arshsisodiya/helios-mirror#125]
Getting last-api error every time even after redeploying multiple times by checking appname and upstreamRepo
Any fix for this issue

Logs - 

Starting process with command `bash start.sh`
2022-09-09T09:07:03.305302+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-09-09T09:07:05.045354+00:00 app[web.1]: 2022-09-09 09:07:05,045 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-09-09T09:07:05.329410+00:00 app[web.1]: 2022-09-09 09:07:05,328 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
2022-09-09T09:07:06.381607+00:00 app[web.1]: Traceback (most recent call last):
2022-09-09T09:07:06.381638+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-09-09T09:07:06.381729+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-09-09T09:07:06.381731+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-09-09T09:07:06.381807+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-09-09T09:07:06.381809+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-09-09T09:07:06.381874+00:00 app[web.1]:     __import__(pkg_name)
2022-09-09T09:07:06.381876+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 79, in <module>
2022-09-09T09:07:06.381939+00:00 app[web.1]:     srun(["last-api", "-d", "--profile=."])
2022-09-09T09:07:06.381942+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-09-09T09:07:06.382083+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-09-09T09:07:06.382085+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-09-09T09:07:06.382275+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-09-09T09:07:06.382277+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-09-09T09:07:06.382567+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-09-09T09:07:06.382579+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'last-api'
2022-09-09T09:07:06.487445+00:00 app[web.1]: 2022-09-09 09:07:06,487 - asyncio - ERROR - Unclosed client session
2022-09-09T09:07:06.487449+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7f97e9975ed0>
2022-09-09T09:07:06.550068+00:00 app[web.1]: [2022-09-09 09:07:06 +0000] [32] [INFO] Starting gunicorn 20.1.0
2022-09-09T09:07:06.550542+00:00 app[web.1]: [2022-09-09 09:07:06 +0000] [32] [INFO] Listening at: http://0.0.0.0:5674 (32)
2022-09-09T09:07:06.550595+00:00 app[web.1]: [2022-09-09 09:07:06 +0000] [32] [INFO] Using worker: sync
2022-09-09T09:07:06.556036+00:00 app[web.1]: [2022-09-09 09:07:06 +0000] [33] [INFO] Booting worker with pid: 33
2022-09-09T09:07:06.984065+00:00 heroku[web.1]: Process exited with status 1
2022-09-09T09:07:06.792749+00:00 app[web.1]: Traceback (most recent call last):
2022-09-09T09:07:06.792804+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2022-09-09T09:07:06.793064+00:00 app[web.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022-09-09T09:07:06.793090+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
2022-09-09T09:07:06.793253+00:00 app[web.1]:     return _get_module_details(pkg_main_name, error)
2022-09-09T09:07:06.793276+00:00 app[web.1]:   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2022-09-09T09:07:06.793420+00:00 app[web.1]:     __import__(pkg_name)
2022-09-09T09:07:06.793444+00:00 app[web.1]:   File "/usr/src/app/bot/__init__.py", line 79, in <module>
2022-09-09T09:07:06.793573+00:00 app[web.1]:     srun(["last-api", "-d", "--profile=."])
2022-09-09T09:07:06.793603+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 501, in run
2022-09-09T09:07:06.793866+00:00 app[web.1]:     with Popen(*popenargs, **kwargs) as process:
2022-09-09T09:07:06.793891+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
2022-09-09T09:07:06.794229+00:00 app[web.1]:     self._execute_child(args, executable, preexec_fn, close_fds,
2022-09-09T09:07:06.794251+00:00 app[web.1]:   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
2022-09-09T09:07:06.794773+00:00 app[web.1]:     raise child_exception_type(errno_num, err_msg, err_filename)
2022-09-09T09:07:06.794805+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'last-api'
2022-09-09T09:07:06.935698+00:00 app[web.1]: 2022-09-09 09:07:06,935 - asyncio - ERROR - Unclosed client session
2022-09-09T09:07:06.935700+00:00 app[web.1]: client_session: <aiohttp.client.ClientSession object at 0x7f2d45f75ed0>
2022-09-09T09:07:07.054379+00:00 heroku[web.1]: State changed from starting to crashed
2022-09-09T09:07:07.391435+00:00 heroku[web.1]: Process exited with status 1

**Comment by arshsisodiya** [comment]
Delete your Fork and Refork Again
