### ISSUE TITLE
heroku deploy error

### ISSUE THREAD

**Issue by assc0d3r** [arshsisodiya/helios-mirror#17]
warning: no common commits
2022-05-23T13:49:51.604484+00:00 heroku[web.1]: State changed from starting to up
2022-05-23T13:49:51.475724+00:00 app[web.1]: [2022-05-23 13:49:51 +0000] [31] [INFO] Starting gunicorn 20.1.0
2022-05-23T13:49:51.476114+00:00 app[web.1]: [2022-05-23 13:49:51 +0000] [31] [INFO] Listening at: http://0.0.0.0:6238 (31)
2022-05-23T13:49:51.476176+00:00 app[web.1]: [2022-05-23 13:49:51 +0000] [31] [INFO] Using worker: aiohttp.GunicornWebWorker
2022-05-23T13:49:51.479605+00:00 app[web.1]: [2022-05-23 13:49:51 +0000] [59] [INFO] Booting worker with pid: 59
2022-05-23T13:49:52.787915+00:00 heroku[web.1]: Process exited with status 1
2022-05-23T13:49:52.556595+00:00 app[web.1]: 2022-05-23 13:49:52,556 - root - WARNING - Mirror Logs Chat Details not provided! Proceeding Without it
2022-05-23T13:49:52.556654+00:00 app[web.1]: 2022-05-23 13:49:52,556 - root - WARNING - LINK_LOGS Chat id not provided, Proceeding Without it
2022-05-23T13:49:52.556728+00:00 app[web.1]: 2022-05-23 13:49:52,556 - root - WARNING - Leech Log Channel ID not Provided! You will not be able to use leech features
2022-05-23T13:49:52.556786+00:00 app[web.1]: 2022-05-23 13:49:52,556 - bot - ERROR - AUTO_DELETE_UPLOAD_MESSAGE_DURATION var missing! Exiting now
2022-05-23T13:49:52.625240+00:00 app[web.1]: Exception ignored in: <function ClientSession.__del__ at 0x7f5e043f0670>
2022-05-23T13:49:52.625242+00:00 app[web.1]: Traceback (most recent call last):
2022-05-23T13:49:52.625243+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 347, in __del__
2022-05-23T13:49:52.625243+00:00 app[web.1]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 1740, in call_exception_handler
2022-05-23T13:49:52.625243+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
2022-05-23T13:49:52.625245+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
2022-05-23T13:49:52.625245+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
2022-05-23T13:49:52.625246+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
2022-05-23T13:49:52.625246+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
2022-05-23T13:49:52.625246+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1186, in emit
2022-05-23T13:49:52.625247+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
2022-05-23T13:49:52.625247+00:00 app[web.1]: NameError: name 'open' is not defined
2022-05-23T13:49:52.854498+00:00 heroku[web.1]: State changed from up to crashed
2022-05-23T13:49:58.343618+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=artheliosleech.herokuapp.com request_id=ccfcd24c-975e-4f76-899a-9bfd3990e93e fwd="23.22.179.40" dyno=web.1 connect=5000ms service= status=503 bytes= protocol=https

**Comment by arshsisodiya** [comment]
open your eyes and read the logs "AUTO_DELETE_UPLOAD_MESSAGE_DURATION var missing! Exiting now"

P.s - Don't Eat Charas while deploying.

**Comment by assc0d3r** [comment]
thanks for the reply any solution to the NameError: name 'open' is not defined still persisting any input regarding the same is much appreciated
