### ISSUE TITLE
'open' is not defined

### ISSUE THREAD

**Issue by annyxd01** [arshsisodiya/helios-mirror#51]
I am receiving This error On Heroku 
```
2022-06-22T13:59:31.357899+00:00 heroku[web.1]: State changed from starting to up
2022-06-22T13:59:31.350514+00:00 app[web.1]: 2022-06-22 13:59:31,350 - bot - ERROR - One or more env variables missing! Exiting now
2022-06-22T13:59:31.547262+00:00 app[web.1]: Exception ignored in: <function ClientSession.__del__ at 0x7fb6d0d079d0>
2022-06-22T13:59:31.547264+00:00 app[web.1]: Traceback (most recent call last):
2022-06-22T13:59:31.547265+00:00 app[web.1]:   File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 347, in __del__
2022-06-22T13:59:31.547265+00:00 app[web.1]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 1740, in call_exception_handler
2022-06-22T13:59:31.547266+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1475, in error
2022-06-22T13:59:31.547266+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
2022-06-22T13:59:31.547266+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
2022-06-22T13:59:31.547267+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
2022-06-22T13:59:31.547267+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
2022-06-22T13:59:31.547268+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1186, in emit
2022-06-22T13:59:31.547268+00:00 app[web.1]:   File "/usr/lib/python3.8/logging/__init__.py", line 1176, in _open
2022-06-22T13:59:31.547268+00:00 app[web.1]: NameError: name 'open' is not defined
2022-06-22T13:59:31.891141+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by Arata74** [comment]
check config

**Comment by arshsisodiya** [comment]
Check your configs and Read the README, it's there for a reason.
