### ISSUE TITLE
Bots Getting stuck ,at status failed ,cleaning download 

### ISSUE THREAD

**Issue by RealNoobieDrive** [arshsisodiya/helios-mirror#54]
Name: [METADATA]Fear+the+Walking+Dead+Seasons+1-4+Complete+(1080p+BluRay+x265+HEVC+10bit+TrueHD+5.1)+Posix-Hoxlund
Status: Failed 🚫. Cleaning Download...
[▱▱▱▱▱▱▱▱▱▱▱▱] 0.00%
Downloaded: 0B of 0.00 B
Speed: 0.00 B/s | ETA: -
Seeders: 0 | Peers: 0
Source Msg: Click Here (https://t.me/c/1252345037/127247)
User: ️Aqeel️(5124474534)
To Stop:/cancel2 f5d4ff935c7bede2

CPU: 3.1% | FREE: 414.23GB
RAM: 28.8% | UPTIME: 3h48m13s
DL: 0B/s | UL: 0B/s

**Comment by arshsisodiya** [comment]
Your Torrent issue, Try with another torrent

**Comment by RealNoobieDrive** [comment]
2022-06-23 06:23:36,993 - bot - INFO - Cancelling Download: [METADATA]Fear+the+Walking+Dead+Seasons+1-4+Complete+(1080p+BluRay+x265+HEVC+10bit+TrueHD+5.1)+Posix-Hoxlund
2022-06-23 06:23:37,087 - bot - WARNING - Message to delete not found
2022-06-23 06:23:37,087 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/cancel_mirror.py", line 45, in cancel_mirror
    dl.download().cancel_download()
  File "/usr/src/app/bot/helper/mirror_utils/status_utils/aria_download_status.py", line 98, in cancel_download
    self.__listener.onDownloadError('Download stopped by user!')
  File "/usr/src/app/bot/modules/mirror.py", line 187, in onDownloadError
    error = error.replace('<', ' ').replace('>', ' ')
UnboundLocalError: local variable 'error' referenced before assignment
2022-06-23 06:24:11,886 - bot - WARNING - Message to delete not found

**Comment by RealNoobieDrive** [comment]
is it due it mirror msg was deleted ??
