### ISSUE TITLE
Mega Premium Account Problem

### ISSUE THREAD

**Issue by PBhadoo** [arshsisodiya/helios-mirror#76]
I've tried several repos, but mega premium accounts are not working.

2022-07-07 06:21:28,833 - bot - ERROR - Mega download error in file DOWNLOAD 9. MongoDB Installation.pdf: Over quota
2022-07-07 06:21:28,833 - bot - ERROR - Mega download error in file DOWNLOAD 11. Populating the DB.zip: Over quota

While starting BOT, it doesn't even login Mega.

````
2022-07-07 06:21:00,087 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
[2022-07-07 06:21:02 +0000] [48] [INFO] Starting gunicorn 20.1.0
[2022-07-07 06:21:02 +0000] [48] [INFO] Listening at: http://0.0.0.0:80 (48)
[2022-07-07 06:21:02 +0000] [48] [INFO] Using worker: sync
[2022-07-07 06:21:02 +0000] [51] [INFO] Booting worker with pid: 51
2022-07-07 06:21:03,779 - bot - INFO - Generating BOT_SESSION_STRING
2022-07-07 06:21:03,781 - root - INFO - Initializing Aria2c
2022-07-07 06:21:05,283 - root - WARNING - BASE_URL_OF_BOT not provided!
2022-07-07 06:21:06,703 - bot - INFO - Creating Telegraph Account
2022-07-07 06:21:11,557 - apscheduler.scheduler - INFO - Scheduler started
2022-07-07 06:21:11,661 - bot - INFO - Bot Started!
````

**Comment by PBhadoo** [comment]
I tried doing things again. Mega Worked Login.

but shows error when i try to download something.

````
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
TypeError: add_download() takes 3 positional arguments but 4 were given
````

**Comment by arshsisodiya** [comment]
If you using Master Branch make sure to set MEGAREST = "True", than mega will work, I'm using Mega Premium Account and it's working fine for me

**Comment by arshsisodiya** [comment]
> Still getting same.
> 
> ```
> root@instance-1:/home/bhadoo/bot# sudo docker build . -t mirror-bot
> Sending build context to Docker daemon   20.2MB
> Step 1/7 : FROM arshsisodiya/helioskirepo:public
>  ---> 5831339ab93e
> Step 2/7 : WORKDIR /usr/src/app
>  ---> Using cache
>  ---> f651722f6eef
> Step 3/7 : RUN chmod 777 /usr/src/app
>  ---> Using cache
>  ---> 59d875143706
> Step 4/7 : COPY requirements.txt .
>  ---> Using cache
>  ---> c4e94c4d7ba8
> Step 5/7 : RUN pip3 install --no-cache-dir -r requirements.txt
>  ---> Using cache
>  ---> 60771794291f
> Step 6/7 : COPY . .
>  ---> 78aa0a8799a8
> Step 7/7 : CMD ["bash", "start.sh"]
>  ---> Running in d85c7c6150bd
> Removing intermediate container d85c7c6150bd
>  ---> 513954b65016
> Successfully built 513954b65016
> Successfully tagged mirror-bot:latest
> root@instance-1:/home/bhadoo/bot# sudo docker run -p 80:80 mirror-bot
> [2022-07-07 09:58:49 +0000] [11] [INFO] Starting gunicorn 20.1.0
> [2022-07-07 09:58:49 +0000] [11] [INFO] Listening at: http://0.0.0.0:80 (11)
> [2022-07-07 09:58:49 +0000] [11] [INFO] Using worker: sync
> [2022-07-07 09:58:49 +0000] [39] [INFO] Booting worker with pid: 39
> 2022-07-07 09:58:49,598 - bot - INFO - Generating BOT_SESSION_STRING
> 2022-07-07 09:58:49,602 - root - INFO - Initializing Aria2c
> Initiliazing Library with API_KEY: T95WyAgb
> 2022/07/07 09:58:51 Serving on :6090
> [GIN] 2022/07/07 - 09:58:58 | 200 |  4.540497471s |       127.0.0.1 | POST     "/login"
> 2022-07-07 09:58:59,570 - bot - INFO - Creating Telegraph Account
> 2022-07-07 09:59:00,737 - apscheduler.scheduler - INFO - Scheduler started
> 2022-07-07 09:59:00,842 - bot - INFO - Bot Started!
> 2022-07-07 09:59:22,210 - bot - INFO - https://mega.nz/folder/vvwAGY4Y#02n9_qEc3hqNVqbFP98YCA
> Exception in thread Thread-4:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
> TypeError: add_download() takes 3 positional arguments but 4 were given
> ```

In this Your mega is logged inand you probably facing this error because you changed something,

Try using without changing anything and just Keep MEGAREST = "True"

**Comment by PBhadoo** [comment]
Yeah, Mega login is now working. I tried Setting Your Repo as upstream, then removing the sample config. still same issue.

**Comment by PBhadoo** [comment]
I am on GCP, not on Heroku.
